#
# Generated by the NeXT Project Builder.
#
# NOTE: Do NOT change this file -- Project Builder maintains it.
#
# Put all of your customizations in files called Makefile.preamble
# and Makefile.postamble (both optional), and Makefile will include them.
#

NAME = NXMines

PROJECTVERSION = 2.6
PROJECT_TYPE = Application
LANGUAGE = English

NEXTSTEP_APPICON = NXMines.tiff
ICONSECTIONS =	-sectcreate __ICON app NXMines.tiff

LOCAL_RESOURCES = NXMines.nib

GLOBAL_RESOURCES = brick8.tiff NXMines.tiff brick7.tiff brick6.tiff\
                   brickPushedAndNoBomb.tiff brick1.tiff brick5.tiff\
                   brick4.tiff HighScores.tiff brick3.tiff brick2.tiff\
                   smilee.tiff brickPushedAndFalseBomb.tiff\
                   brickPushedAndBomb.tiff brickAndFlag.tiff\
                   brickPushed.tiff NXMines5.tiff brick.tiff

CLASSES = MineButton.m MyApp.m NXMineView.m

HFILES = MineButton.h MyApp.h NXMineView.h

MFILES = NXMines_main.m

OTHERSRCS = Makefile.preamble Makefile Makefile.postamble m.template\
            h.template


MAKEFILEDIR = $(NEXT_ROOT)/NextDeveloper/Makefiles/pb_makefiles
CODE_GEN_STYLE = DYNAMIC
MAKEFILE = app.make
NEXTSTEP_INSTALLDIR = $(HOME)/Apps
WINDOWS_INSTALLDIR = /MyApps
LIBS = 
DEBUG_LIBS = $(LIBS)
PROF_LIBS = $(LIBS)


FRAMEWORKS = -framework AppKit -framework Foundation


include $(MAKEFILEDIR)/platform.make

-include Makefile.preamble

include $(MAKEFILEDIR)/$(MAKEFILE)

-include Makefile.postamble

-include Makefile.dependencies
