#
# Generated by the NeXT Project Builder.
#
# NOTE: Do NOT change this file -- Project Builder maintains it.
#
# Put all of your customizations in files called Makefile.preamble
# and Makefile.postamble (both optional), and Makefile will include them.
#

NAME = NXMines

PROJECTVERSION = 1.1
LANGUAGE = English

APPICON = NXMines.tiff
LOCAL_RESOURCES = NXMines.nib

GLOBAL_RESOURCES = brick.tiff brick1.tiff brick2.tiff brick3.tiff\
                   brick4.tiff brick5.tiff brick6.tiff brick7.tiff\
                   brick8.tiff brickAndFlag.tiff brickPushed.tiff\
                   brickPushedAndBomb.tiff brickPushedAndFalseBomb.tiff\
                   brickPushedAndNoBomb.tiff HighScores.tiff\
                   NXMines5.tiff smilee.tiff

CLASSES = MyApp.m NXMineView.m

HFILES = MyApp.h NXMineView.h

MFILES = NXMines_main.m

OTHERSRCS = Makefile.preamble Makefile Makefile.postamble


MAKEFILEDIR = /NextDeveloper/Makefiles/app
MAKEFILE = app.make
INSTALLDIR = $(HOME)/Apps
INSTALLFLAGS = -c -s -m 755
SOURCEMODE = 444

ICONSECTIONS =	-sectcreate __ICON app NXMines.tiff

LIBS = -lMedia_s -lNeXT_s
DEBUG_LIBS = $(LIBS)
PROF_LIBS = $(LIBS)


-include Makefile.preamble

include $(MAKEFILEDIR)/$(MAKEFILE)

-include Makefile.postamble

-include Makefile.dependencies
